on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container: node:16  # Aquí cumples con "tecnología de tu preferencia"
    steps:
      - uses: actions/checkout@v3 # PRIMERO descargamos el código
      
      - run: echo "Evidencia de Actividad - Victoria"
      - run: node --version
      - run: npm --version
      
      # Esto ejecuta tu archivo app.js dentro del contenedor
      - run: node app.js